GET http://localhost:8000/users

###
GET http://localhost:8000/users/6238aba76377cd115a6e3720


###
POST http://localhost:8000/users/
Content-Type: application/json

{
    "user_id": "12223223",
    "email": "Kisiel.com",
    "password":"lol123",
    "user_name":"Kisiel"
}

###
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "email": "Kisiel@gmail.com",
    "password":"lol123"
}

###

PATCH http://localhost:8000/users/6238b8ca28924c330593743f
Content-Type: application/json

{
    "user_name": "Kiss"
}

###
DELETE http://localhost:8000/users/6238b8ca28924c330593743f

###