GET http://localhost:8000/users

###
GET http://localhost:8000/users/623b4da33a549673095c14e2




###
POST http://localhost:8000/users/register
Content-Type: application/json

{
    "user_id": "ere3223",
    "email": "Kiiejl.com",
    "hashed_password":"lko23",
    "user_name":"Kielkl"
}

###
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "email": "Kisiel@gmail.com",
    "hashed_password":"lol123"
}

###

DELETE http://localhost:8000/users/6230c1c6b9157472cce3c252


###
PATCH http://localhost:8000/users/623b4da33a549673095c14e2
Content-Type: application/json

{
    "username": "Yazan"
}